# Sokoban
# config.py

FPS = 60

MAZE_HOR = 13
MAZE_VER = 13
TILES_HOR = 2*MAZE_HOR + 1 #25
TILES_VER = 2*MAZE_VER + 1 #20

UP_MARGIN = 0
DOWN_MARGIN = 0
LEFT_MARGIN = 0
RIGHT_MARGIN = 0

TILE_SIZE = 32

SCREEN_WIDTH = TILES_HOR * TILE_SIZE #800
SCREEN_HEIGHT = TILES_VER * TILE_SIZE #640

# Delay between Moves
MAX_DELAY = 6
