# Maze
# config.py

FPS = 60

MAZE_HOR = 13
MAZE_VER = 13
TILES_HOR = 2*MAZE_HOR + 1 #27
TILES_VER = 2*MAZE_VER + 1 #27

TILE_SIZE = 32

UP_MARGIN = 1*TILE_SIZE
DOWN_MARGIN = 1*TILE_SIZE
LEFT_MARGIN = 4*TILE_SIZE
RIGHT_MARGIN = 4*TILE_SIZE

MAZE_SCREEN_WIDTH = TILES_HOR * TILE_SIZE #864
MAZE_SCREEN_HEIGHT = TILES_VER * TILE_SIZE #864

SCREEN_WIDTH = LEFT_MARGIN + MAZE_SCREEN_WIDTH + RIGHT_MARGIN
SCREEN_HEIGHT = UP_MARGIN + MAZE_SCREEN_HEIGHT + DOWN_MARGIN

# Delay between Moves
MAX_DELAY = 6